version: '3.4'

services:
  webapi:
    image: webapi:dev
    container_name: WebAPI
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "WebAPI"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - /Users/geovane/Library/Mobile Documents/com~apple~CloudDocs/Documents/Course Dev/WebApi_Docker/WebAPI:/app
      - /Users/geovane/Library/Mobile Documents/com~apple~CloudDocs/Documents/Course Dev/WebApi_Docker/WebAPI:/src
      - /Users/geovane/vsdbg/vs2017u5:/remote_debugger:rw
      - /Users/geovane/.nuget/packages/:/root/.nuget/packages:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net5.0/WebAPI.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true